config/routes.rb
Questions::Application.routes.draw do
  devise_for :users

  resources :questions
  match 'questions/:id/answer' => 'questions#answer', :as => 'answer_question'

  root :to => 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base

  ANSWER_TYPES = {
    'text' => 1,
    'website' => 2
  }

  attr_accessible :answer, :inquiry, :answer_type, :next

  validates :answer, :presence => true
  validates :inquiry, :presence => true
  validates :answer_type, :presence => true, 
            :inclusion => {:in => ANSWER_TYPES.values}

  def self.find_first
    # Finds questions which are not next to any other question
    self.where("id NOT IN (?)", self.select(:next).map(&:next))
  end

  def self.find_last
    # Finds the question which is next to itself, meaning it's the last one
    self.where("id == next")
  end

  def self.answer_types
    ANSWER_TYPES
  end

  # Returns a list of question [inquires, id] for display
  def self.question_names question
    questions = self.all
    # puts a '*' next to the question passed as parameter
    questions = questions.map { |q| [ (q == question ? '*' : '') + q.inquiry, q.id] }
  end

  def answer_type_name
    ANSWER_TYPES.invert[answer_type]
  end

  def match a
    regexp = Regexp.new(answer.downcase)
    regexp.match(a.downcase.strip) ? true : false
  end

  # Returns the question next to the current one
  def get_next
    self.class.find(self.next)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :answer]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save

        # If question points to no one question, point to itself
        @question.next ||= @question.id
        @question.save

        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  # POST /questions/answer/1
  def answer
    @question = Question.find(params[:id])
    right = @question.match(params[:answer])

    if right
     flash[:notice] = 'That is right!'
    else
      flash[:error] = 'Try again!'
    end

    redirect_to questions_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questions</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>
<p id="error"><%= flash[:error] %></p>

<%= yield %>

</body>
</html>

app/views/questions/_answer.html.erb
<%= form_tag :method => 'post', :action => 'answer', :id => id do %>
    <%= text_field_tag 'answer' %>
    <%= submit_tag 'Go' %>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inquiry %><br />
    <%= f.text_field :inquiry %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :answer_type %><br />
    <%= f.select :answer_type, Question.answer_types %>
  </div>

  <div class="field">
    <%= f.label :next %><br />
    <%= f.select :next, Question.question_names(@question) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Inquiry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.inquiry %></td>

    <% if current_user %>
      <td><%= link_to 'Show', question %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
      <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>

    <td> <%= render :partial => 'answer', :locals => { :id => question.id } %> </td>

  </tr>
<% end %>
</table>

<br />

<% if current_user %>
  <%= link_to 'New Question', new_question_path %>
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <b>Inquiry:</b>
  <%= @question.inquiry %>
</p>

<p>
  <b>Answer:</b>
  <%= @question.answer %>
</p>

<p>
  <b>Type:</b>
  <%= @question.answer_type_name %>
</p>

<p>
  <b>Next:</b>
  <%= @question.get_next.inquiry %>
</p>

<p>
    <b>Answer it</b>: <%= render :partial => 'answer', :locals => { :id => @question.id } %>
</p>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>